version: '3.7'

services:
  frontend:
    image: nginx:alpine
    container_name: nginx_frontend
    ports:
      - "8082:80"
    # network_mode: host
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  webnet:
    driver: bridge
