version: '3'

services:
  backend:
    container_name: backend
    ports:
      - "5000:5000"
    image: python:3.10
    restart: always
    volumes:
      - ./app:/app
    working_dir: /app
    command: /bin/bash -c "pip3 install -r /app/requirements.txt && python3 main.py"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 100M
  