version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gami_db
    restart: always
    env_file:
      - .env

    ports:
      - "5437:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
      - gami_db_data:/var/lib/postgresql/data
    # network_mode: host

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "gamiadmin@niias.ru"
  #     PGADMIN_DEFAULT_PASSWORD: "gamiadmin"

volumes:
  gami_db_data:
    driver: local
  # pgadmin-data:
